import {
  User,
  Patient,
  Appointment,
  Consultation,
  Prescription,
  LabRequest,
  BillingInvoice,
  SystemNotification,
  NurseTriageRecord,
  SmsEmailLog,
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'pat-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@example.com',
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    title: 'Patient',
    phone: '+254 712 345678',
    password: 'patient123',
  },
  {
    id: 'doc-1',
    name: 'Dr. Alex Mercer',
    email: 'alex.mercer@smartclinic.co.ke',
    role: 'doctor',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150',
    title: 'Consultant Physician & Cardiologist',
    phone: '+254 722 876543',
    specialty: 'General Medicine & Cardiology',
    department: 'Outpatient Care',
    password: 'doctor123',
  },
  {
    id: 'nurse-1',
    name: 'Nurse Riley Davis',
    email: 'riley.davis@smartclinic.co.ke',
    role: 'nurse',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150',
    title: 'Senior Triage Nurse',
    phone: '+254 733 456789',
    department: 'Triage & Vital Assessment Station',
    password: 'nurse123',
  },
  {
    id: 'recep-1',
    name: 'Kevin Otieno',
    email: 'kevin.otieno@smartclinic.co.ke',
    role: 'receptionist',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150',
    title: 'Front Desk & Patient Onboarding Officer',
    phone: '+254 701 234567',
    department: 'Reception & Registration',
    password: 'reception123',
  },
  {
    id: 'admin-1',
    name: 'Chloe Bennett',
    email: 'chloe.bennett@smartclinic.co.ke',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    title: 'Clinic Operations Director',
    phone: '+254 711 999888',
    department: 'Administration & Compliance',
    password: 'admin2026',
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    mrn: 'MRN-2026-0041',
    name: 'Sarah Jenkins',
    age: 34,
    gender: 'Female',
    dob: '1992-05-14',
    phone: '+254 712 345678',
    email: 'sarah.jenkins@example.com',
    address: 'Kilimani, Nairobi, Kenya',
    bloodGroup: 'A+',
    allergies: ['Penicillin', 'Peanuts'],
    medicalHistory: ['Mild Asthma (2018)', 'Hypertension Stage 1 (2023)'],
    insurance: {
      provider: 'NHIF / SHA Kenya',
      policyNumber: 'NHIF-99482103',
      copay: 500,
    },
    emergencyContact: {
      name: 'David Jenkins',
      phone: '+254 712 999999',
      relationship: 'Spouse',
    },
    status: 'Active',
    tempPassword: 'pin-9948',
    activationCode: 'ACT-0041',
    isAccountClaimed: true,
    password: 'patient123',
    nationalId: 'ID-33948120',
    notificationSent: {
      sms: true,
      email: true,
      sentAt: '2026-09-06T10:15:00Z',
    },
  },
  {
    id: 'pat-2',
    mrn: 'MRN-2026-0089',
    name: 'Robert Chen',
    age: 52,
    gender: 'Male',
    dob: '1974-11-20',
    phone: '+254 721 888121',
    email: 'robert.chen@example.com',
    address: 'Westlands, Nairobi, Kenya',
    bloodGroup: 'O+',
    allergies: ['Sulfa Drugs'],
    medicalHistory: ['Type 2 Diabetes (2019)', 'Hyperlipidemia'],
    insurance: {
      provider: 'Jubilee Health Insurance',
      policyNumber: 'JUB-77123901',
      copay: 1000,
    },
    emergencyContact: {
      name: 'Mei Chen',
      phone: '+254 721 888333',
      relationship: 'Daughter',
    },
    status: 'Active',
    tempPassword: 'pin-7712',
    activationCode: 'ACT-0089',
    isAccountClaimed: false,
    notificationSent: {
      sms: true,
      email: true,
      sentAt: '2026-09-06T11:00:00Z',
    },
  },
  {
    id: 'pat-emg-1',
    mrn: 'EMG-2026-9110',
    name: 'Emergency Patient (Male - Unidentified)',
    age: 40,
    gender: 'Male',
    dob: '1986-01-01',
    phone: '+254 700 000000',
    email: 'emergency.triage@smartclinic.co.ke',
    address: 'Brought by Ambulance - Accident Site A104',
    bloodGroup: 'O-',
    allergies: ['Unknown - Emergency Protocols Active'],
    medicalHistory: ['Emergency Stabilization Active'],
    insurance: {
      provider: 'Emergency Care Fund',
      policyNumber: 'EMG-FUND-001',
      copay: 0,
    },
    emergencyContact: {
      name: 'Ambulance Paramedic Unit 4',
      phone: '+254 999',
      relationship: 'First Responder',
    },
    status: 'Emergency-Unverified',
    isEmergency: true,
  },
];

export const MOCK_TRIAGE_RECORDS: NurseTriageRecord[] = [
  {
    id: 'trg-101',
    patientId: 'pat-1',
    patientName: 'Sarah Jenkins',
    nurseId: 'nurse-1',
    nurseName: 'Nurse Riley Davis',
    timestamp: '2026-09-06T09:30:00Z',
    bpSystolic: 124,
    bpDiastolic: 80,
    temperature: 36.7,
    heightCm: 168,
    weightKg: 64.5,
    spo2: 98,
    pulseRate: 72,
    priority: 'Routine',
    chiefComplaintSummary: 'Mild morning tightness in chest and routine blood pressure check.',
    nurseNotes: 'Patient calm and alert. Vitals within normal physiological limits.',
    status: 'Triaged',
  },
  {
    id: 'trg-emg-911',
    patientId: 'pat-emg-1',
    patientName: 'Emergency Patient (Male - Unidentified)',
    nurseId: 'nurse-1',
    nurseName: 'Nurse Riley Davis',
    timestamp: '2026-09-06T10:00:00Z',
    bpSystolic: 90,
    bpDiastolic: 60,
    temperature: 35.8,
    heightCm: 175,
    weightKg: 78.0,
    spo2: 91,
    pulseRate: 115,
    priority: 'Emergency',
    chiefComplaintSummary: 'Blunt chest trauma & acute hypoxia from road traffic accident.',
    nurseNotes: 'HIGH PRIORITY RED FLAG: Oxygen therapy started via non-rebreather mask. IV line established.',
    status: 'Transferred-To-Doctor',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'pat-1',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc-1',
    doctorName: 'Dr. Alex Mercer',
    specialty: 'General Medicine & Cardiology',
    date: '2026-09-06',
    timeSlot: '10:00 AM',
    type: 'In-Person',
    status: 'Triaged-Pending-Doctor',
    reason: 'Routine cardiac evaluation & persistent mild chest tightness.',
    triageRecord: MOCK_TRIAGE_RECORDS[0],
    createdAt: '2026-09-06T09:15:00Z',
  },
  {
    id: 'apt-emg-911',
    patientId: 'pat-emg-1',
    patientName: 'Emergency Patient (Male - Unidentified)',
    doctorId: 'doc-1',
    doctorName: 'Dr. Alex Mercer',
    specialty: 'Emergency Resuscitation & Surgery',
    date: '2026-09-06',
    timeSlot: 'Immediate',
    type: 'Walk-In Emergency',
    status: 'In-Consultation',
    reason: 'CRITICAL EMERGENCY: Road traffic trauma & acute respiratory distress.',
    triageRecord: MOCK_TRIAGE_RECORDS[1],
    createdAt: '2026-09-06T10:00:00Z',
  },
  {
    id: 'apt-102',
    patientId: 'pat-2',
    patientName: 'Robert Chen',
    doctorId: 'doc-1',
    doctorName: 'Dr. Alex Mercer',
    specialty: 'Internal Medicine',
    date: '2026-09-06',
    timeSlot: '11:30 AM',
    type: 'In-Person',
    status: 'In-Nurse-Triage',
    reason: 'Diabetic review & lipid profile checkup.',
    createdAt: '2026-09-06T09:45:00Z',
  },
];

export const MOCK_CONSULTATIONS: Consultation[] = [];
export const MOCK_PRESCRIPTIONS: Prescription[] = [];
export const MOCK_LAB_REQUESTS: LabRequest[] = [];
export const MOCK_BILLING: BillingInvoice[] = [];

export const MOCK_SMS_EMAIL_LOGS: SmsEmailLog[] = [
  {
    id: 'log-101',
    patientName: 'Sarah Jenkins',
    phone: '+254 712 345678',
    email: 'sarah.jenkins@example.com',
    mrn: 'MRN-2026-0041',
    tempPin: 'pin-9948',
    smsStatus: 'Delivered',
    emailStatus: 'Delivered',
    sentAt: '2026-09-06T10:15:00Z',
  },
  {
    id: 'log-102',
    patientName: 'Robert Chen',
    phone: '+254 721 888121',
    email: 'robert.chen@example.com',
    mrn: 'MRN-2026-0089',
    tempPin: 'pin-7712',
    smsStatus: 'Delivered',
    emailStatus: 'Delivered',
    sentAt: '2026-09-06T11:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-emg-1',
    userId: 'doc-1',
    roleTarget: 'doctor',
    title: '🚨 CRITICAL EMERGENCY PATIENT TRIAGED',
    message: 'Nurse Riley Davis triaged Emergency Patient (EMG-2026-9110) with SpO2 91% and BP 90/60. Immediate physician consultation required.',
    type: 'error',
    link: '/consultation/apt-emg-911',
    timestamp: '2026-09-06T10:02:00Z',
    read: false,
  },
  {
    id: 'notif-nurse-1',
    userId: 'nurse-1',
    roleTarget: 'nurse',
    title: 'New Patient Arrived at Reception',
    message: 'Receptionist Kevin checked in Robert Chen (MRN-2026-0089). Please perform triage vitals.',
    type: 'info',
    link: '/nurse/triage',
    timestamp: '2026-09-06T09:46:00Z',
    read: false,
  },
];
